# Generated by Django 5.2 on 2025-05-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact', models.CharField(blank=True, max_length=25, null=True)),
                ('birth', models.CharField(blank=True, max_length=25, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sensorID', models.CharField(max_length=100)),
                ('temperature', models.CharField(blank=True, max_length=100, null=True)),
                ('humidity', models.CharField(blank=True, max_length=100, null=True)),
                ('dust', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('panID', models.CharField(max_length=25)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubo.user')),
            ],
        ),
        migrations.CreateModel(
            name='MoodLightStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('moodlighID', models.CharField(max_length=100)),
                ('ON_OFF', models.BooleanField(blank=True, null=True)),
                ('colorcode', models.CharField(blank=True, max_length=25, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('heaterID', models.CharField(max_length=100)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubo.user')),
            ],
        ),
        migrations.CreateModel(
            name='CryDetection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('cry_label', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.CharField(blank=True, max_length=100, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubo.user')),
            ],
        ),
    ]
